// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartInventory.Models.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public string Stock { get; set; }

    public bool IsDeleted { get; set; }
}