// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartInventory.Models.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string Role { get; set; }

    public string Metadata { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginTime { get; set; }
}